version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: arena_postgres
    environment:
      POSTGRES_USER: local_test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: arena
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: arena_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis-data:


networks:
  app-network:
    driver: bridge
