// <auto-generated />
using System;
using System.Collections.Generic;
using ArenaService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArenaService.Migrations
{
    [DbContext(typeof(ArenaDbContext))]
    [Migration("20250116055802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArenaService.Models.AvailableOpponents", b =>
                {
                    b.Property<string>("AvatarAddress")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("avatar_address");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer")
                        .HasColumnName("round_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<List<string>>("OpponentAvatarAddresses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("opponent_avatar_addresses");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("AvatarAddress", "RoundId")
                        .HasName("pk_available_opponents");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_available_opponents_round_id");

                    b.ToTable("available_opponents", (string)null);
                });

            modelBuilder.Entity("ArenaService.Models.AvailableOpponentsRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarAddress")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("avatar_address");

                    b.Property<int>("CostPaid")
                        .HasColumnType("integer")
                        .HasColumnName("cost_paid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<List<string>>("RequestedOpponentAddresses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("requested_avatar_addresses");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer")
                        .HasColumnName("round_id");

                    b.Property<string>("TxId")
                        .HasColumnType("text")
                        .HasColumnName("tx_id");

                    b.Property<int?>("TxStatus")
                        .HasColumnType("integer")
                        .HasColumnName("tx_status");

                    b.Property<int>("UpdateSource")
                        .HasColumnType("integer")
                        .HasColumnName("update_source");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_available_opponents_requests");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_available_opponents_requests_round_id");

                    b.ToTable("available_opponents_requests", (string)null);
                });

            modelBuilder.Entity("ArenaService.Models.BattleLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttackerAvatarAddress")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("attacker_avatar_address");

                    b.Property<long?>("BattleBlockIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("battle_block_index");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("DefenderAvatarAddress")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("defender_avatar_address");

                    b.Property<bool?>("IsVictory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_victory");

                    b.Property<int?>("OpponentScoreChange")
                        .HasColumnType("integer")
                        .HasColumnName("opponent_score_change");

                    b.Property<int?>("ParticipantScoreChange")
                        .HasColumnType("integer")
                        .HasColumnName("participant_score_change");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("TxId")
                        .HasColumnType("text")
                        .HasColumnName("tx_id");

                    b.Property<int?>("TxStatus")
                        .HasColumnType("integer")
                        .HasColumnName("tx_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_battle_logs");

                    b.HasIndex("AttackerAvatarAddress", "SeasonId")
                        .HasDatabaseName("ix_battle_logs_attacker_avatar_address_season_id");

                    b.HasIndex("DefenderAvatarAddress", "SeasonId")
                        .HasDatabaseName("ix_battle_logs_defender_avatar_address_season_id");

                    b.ToTable("battle_logs", (string)null);
                });

            modelBuilder.Entity("ArenaService.Models.Participant", b =>
                {
                    b.Property<string>("AvatarAddress")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("avatar_address");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<int>("InitializedScore")
                        .HasColumnType("integer")
                        .HasColumnName("initialized_score");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("AvatarAddress", "SeasonId")
                        .HasName("pk_participants");

                    b.HasIndex("AvatarAddress")
                        .HasDatabaseName("ix_participants_avatar_address");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_participants_season_id");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("ArenaService.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<long>("EndBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("end_block");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<long>("StartBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("start_block");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rounds");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_rounds_season_id");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("ArenaService.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<long>("EndBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("end_block");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.Property<long>("StartBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("start_block");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("ArenaService.Models.User", b =>
                {
                    b.Property<string>("AvatarAddress")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("avatar_address");

                    b.Property<string>("AgentAddress")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("agent_address");

                    b.Property<long>("Cp")
                        .HasColumnType("bigint")
                        .HasColumnName("cp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("NameWithHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_with_hash");

                    b.Property<int>("PortraitId")
                        .HasColumnType("integer")
                        .HasColumnName("portrait_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("AvatarAddress")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ArenaService.Models.AvailableOpponents", b =>
                {
                    b.HasOne("ArenaService.Models.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_available_opponents_rounds_round_id");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ArenaService.Models.AvailableOpponentsRequest", b =>
                {
                    b.HasOne("ArenaService.Models.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_available_opponents_requests_rounds_round_id");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ArenaService.Models.BattleLog", b =>
                {
                    b.HasOne("ArenaService.Models.Participant", "Attacker")
                        .WithMany()
                        .HasForeignKey("AttackerAvatarAddress", "SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_battle_logs_participants_attacker_avatar_address_season_id");

                    b.HasOne("ArenaService.Models.Participant", "Defender")
                        .WithMany()
                        .HasForeignKey("DefenderAvatarAddress", "SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_battle_logs_participants_defender_avatar_address_season_id");

                    b.Navigation("Attacker");

                    b.Navigation("Defender");
                });

            modelBuilder.Entity("ArenaService.Models.Participant", b =>
                {
                    b.HasOne("ArenaService.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("AvatarAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participants_users_avatar_address");

                    b.HasOne("ArenaService.Models.Season", "Season")
                        .WithMany("Participants")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participants_seasons_season_id");

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArenaService.Models.Round", b =>
                {
                    b.HasOne("ArenaService.Models.Season", "Season")
                        .WithMany("Rounds")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rounds_seasons_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ArenaService.Models.Season", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
